name: Get youtube videos

on:
  schedule:
    - cron: '0 5 */15 * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest youtube posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/channel/UC9PtEl8I9hbxQwBgJuRyvTA/videos"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "dd/mm/yyyy"
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          committer_email: "alwinjohn231@gmail.com"